Add definition for macOS build
The build failed with,

In file included from ctestenums.cc:2:
In file included from ./include/api/peerconnectioninterface.h:78:
...
In file included from ./include/rtc_base/ipaddress.h:29:
./include/rtc_base/byteorder.h:80:10: fatal error: 'endian.h' file not found

because the build variable WEBRTC_MAC is undefined when that header is
included with the library.

Should maybe report this upstream?