Update to branch-heads/64.
Currently at commit 88f5d9180eae78a6162cccd78850ff416eb82483.

The biggest change is that header files are no longer in a webrtc/
subdirectory. Here is the upstream change:
https://webrtc.googlesource.com/src/+/bb547203bfebcc478b263c4e9ca173c6fd5a0c5d

The signatures for PeerConnectionObserver and
CreatePeerConnectionFactory are slightly changed. I took the examples of
CreateBuiltinAudioEncoderFactory and CreateBuiltinAudioDecoderFactory
from
https://chromium.googlesource.com/external/webrtc/+/32df86ee0e1d892223f6915cd39ab9cb026d9695

This version of WebRTC seems to prefer to link with a bundled copy of
libc++ (libcxx) by default. We set use_custom_libcxx=false in order to
link with libstdc++ like before.

The build automatically used the c++11 ABI, such that I got link errors
(e.g. "undefined reference to `webrtc::JsepSessionDescription::JsepSessionDescription(std::string const&)'").
So remove the manual setting of _GLIBCXX_USE_CXX11_ABI=0 in .pc files.